version: '3.7'
services:
  java:
    build:
      context: .
    network_mode: host
    environment:
      SERVER_URL: https://train.skillerwhale.com
      GO111MODULES: 'on'
      WATCHER_BASE_PATH: /app
      ATTENDANCE_ID_FILE: /app/sync/attendance_id
      WATCHED_EXTS: |
        ["go", "mod", "command_history"]
      IGNORE_DIRS: |
        [".git", "bin"]
    volumes:
      - ./exercises:/app/exercises
      - ./attendance_id:/app/sync/attendance_id
    stdin_open: true
    tty: true
